### ISSUE TITLE
String graph

### ISSUE THREAD

**Issue by 89z** [yourbasic/graph#10]
I see `int` graph here:

https://pkg.go.dev/github.com/yourbasic/graph#New

but no `string` graph

**Comment by korthaj** [comment]
I'm not sure what you're looking for here.  The int in the New function indicates the number of Vertices in the new graph.

**Comment by ruckc** [comment]
@korthaj - i think he wants the vertices in the graph to be `string` instead of `int`.  In my usage, i just have a `map[string]int` sitting beside my graph to do the lookup.
